// Code generated by the Lingua Franca compiler from:
// file://home/foobar/EZ2C-Fall23/lf-3pi/fed-gen/Federation/src/federate__p.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/home/foobar/EZ2C-Fall23/lf-3pi/fed-gen/Federation/src-gen/federate__p"

#include <limits.h>
#include "include/core/platform.h"
#include "include/api/api.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/threaded/scheduler.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
#include "include/core/federated/federate.h"
#include "include/core/federated/net_common.h"
int main(int argc, const char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
const char* _lf_default_argv[] = { "dummy", "-k", "true" };
void _lf_set_default_command_line_options() {
        default_argc = 3;
        default_argv = _lf_default_argv;
}
#include "_print.h"
#include "_networkreceiver_0.h"
#include "_networkreceiver_1.h"
#include "__pin1.h"
#include "__pin2.h"
#include "_federate__p_main.h"
typedef enum {
    federate__p_main,
    _num_enclaves
} _enclave_id;
// The global array of environments associated with each enclave
environment_t envs[_num_enclaves];
// 'Create' and initialize the environments in the program
void _lf_create_environments() {
    environment_init(&envs[federate__p_main],federate__p_main,_lf_number_of_workers,0,2,0,0,4,0,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) envs;
   return _num_enclaves;
}
#include "include/_federate__p_preamble.h"
// No watchdogs found.
typedef void watchdog_t;
watchdog_t* _lf_watchdogs = NULL;
int _lf_watchdog_count = 0;
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _federate__p_main_main_self_t* federate__p_main_self[1];
    SUPPRESS_UNUSED_WARNING(federate__p_main_self);
    _print_self_t* federate__p_p_self[1];
    SUPPRESS_UNUSED_WARNING(federate__p_p_self);
    _networkreceiver_0_self_t* federate__p_nr_federate__p_self[1];
    SUPPRESS_UNUSED_WARNING(federate__p_nr_federate__p_self);
    _networkreceiver_1_self_t* federate__p_nr_federate__p_0_self[1];
    SUPPRESS_UNUSED_WARNING(federate__p_nr_federate__p_0_self);
    __pin1_self_t* federate__p__pin10_self[1];
    SUPPRESS_UNUSED_WARNING(federate__p__pin10_self);
    __pin2_self_t* federate__p__pin20_self[1];
    SUPPRESS_UNUSED_WARNING(federate__p__pin20_self);
    // ***** Start initializing federate__p of class federate__p
    federate__p_main_self[0] = new__federate__p_main();
    federate__p_main_self[0]->base.environment = &envs[federate__p_main];
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
    {
        // ***** Start initializing federate__p.p of class Print
        federate__p_p_self[0] = new__print();
        federate__p_p_self[0]->base.environment = &envs[federate__p_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        federate__p_p_self[0]->_lf_in1_width = -2;
        // width of -2 indicates that it is not a multiport.
        federate__p_p_self[0]->_lf_in2_width = -2;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        federate__p_p_self[0]->_lf__reaction_0.deadline = NEVER;
        federate__p_p_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing federate__p.p
    }
    {
        // ***** Start initializing federate__p.nr_federate__p of class NetworkReceiver_0
        federate__p_nr_federate__p_self[0] = new__networkreceiver_0();
        federate__p_nr_federate__p_self[0]->base.environment = &envs[federate__p_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        federate__p_nr_federate__p_self[0]->_lf_msg_width = -2;
        envs[federate__p_main].startup_reactions[startup_reaction_count[federate__p_main]++] = &federate__p_nr_federate__p_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
        // Initializing action federate__p.nr_federate__p.networkMessage
        federate__p_nr_federate__p_self[0]->_lf__networkMessage.offset = 0;
        federate__p_nr_federate__p_self[0]->_lf__networkMessage.period = -1;
        federate__p_nr_federate__p_self[0]->_lf__networkMessage.mode = NULL;
        _lf_initialize_template((token_template_t*)
                &(federate__p_nr_federate__p_self[0]->_lf__networkMessage),
        sizeof(int));
        federate__p_nr_federate__p_self[0]->_lf__networkMessage.status = absent;
        federate__p_nr_federate__p_self[0]->_lf__reaction_0.deadline = NEVER;
        federate__p_nr_federate__p_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing federate__p.nr_federate__p
    }
    {
        // ***** Start initializing federate__p.nr_federate__p_0 of class NetworkReceiver_1
        federate__p_nr_federate__p_0_self[0] = new__networkreceiver_1();
        federate__p_nr_federate__p_0_self[0]->base.environment = &envs[federate__p_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        federate__p_nr_federate__p_0_self[0]->_lf_msg_width = -2;
        envs[federate__p_main].startup_reactions[startup_reaction_count[federate__p_main]++] = &federate__p_nr_federate__p_0_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
        // Initializing action federate__p.nr_federate__p_0.networkMessage
        federate__p_nr_federate__p_0_self[0]->_lf__networkMessage.offset = 0;
        federate__p_nr_federate__p_0_self[0]->_lf__networkMessage.period = -1;
        federate__p_nr_federate__p_0_self[0]->_lf__networkMessage.mode = NULL;
        _lf_initialize_template((token_template_t*)
                &(federate__p_nr_federate__p_0_self[0]->_lf__networkMessage),
        sizeof(int));
        federate__p_nr_federate__p_0_self[0]->_lf__networkMessage.status = absent;
        federate__p_nr_federate__p_0_self[0]->_lf__reaction_0.deadline = NEVER;
        federate__p_nr_federate__p_0_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing federate__p.nr_federate__p_0
    }
    {
        // ***** Start initializing federate__p._pin10 of class _pin1
        federate__p__pin10_self[0] = new___pin1();
        federate__p__pin10_self[0]->base.environment = &envs[federate__p_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        federate__p__pin10_self[0]->_lf_port_width = -2;
        // width of -2 indicates that it is not a multiport.
        federate__p__pin10_self[0]->_lf_port0_width = -2;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        //***** End initializing federate__p._pin10
    }
    {
        // ***** Start initializing federate__p._pin20 of class _pin2
        federate__p__pin20_self[0] = new___pin2();
        federate__p__pin20_self[0]->base.environment = &envs[federate__p_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        federate__p__pin20_self[0]->_lf_port_width = -2;
        // width of -2 indicates that it is not a multiport.
        federate__p__pin20_self[0]->_lf_port0_width = -2;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        //***** End initializing federate__p._pin20
    }
    //***** End initializing federate__p
    // **** Start deferred initialize for federate__p
    {
    
    
    
        // **** Start deferred initialize for federate__p.p
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of federate__p.p.
            federate__p_p_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of federate__p.p
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of federate__p.p.
            federate__p_p_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of federate__p.p
        
        }
        // **** End of deferred initialize for federate__p.p
        // **** Start deferred initialize for federate__p.nr_federate__p
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of federate__p.nr_federate__p.
            federate__p_nr_federate__p_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of federate__p.nr_federate__p
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of federate__p.nr_federate__p.
            federate__p_nr_federate__p_self[0]->_lf__reaction_1.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            federate__p_nr_federate__p_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &federate__p_nr_federate__p_self[0]->base.allocations);
            federate__p_nr_federate__p_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &federate__p_nr_federate__p_self[0]->base.allocations);
            federate__p_nr_federate__p_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &federate__p_nr_federate__p_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    federate__p_nr_federate__p_self[0]->_lf__reaction_1.output_produced[count++] = &federate__p_nr_federate__p_self[0]->_lf_msg.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of federate__p.nr_federate__p
        
        }
        // **** End of deferred initialize for federate__p.nr_federate__p
        // **** Start deferred initialize for federate__p.nr_federate__p_0
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of federate__p.nr_federate__p_0.
            federate__p_nr_federate__p_0_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of federate__p.nr_federate__p_0
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of federate__p.nr_federate__p_0.
            federate__p_nr_federate__p_0_self[0]->_lf__reaction_1.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            federate__p_nr_federate__p_0_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &federate__p_nr_federate__p_0_self[0]->base.allocations);
            federate__p_nr_federate__p_0_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &federate__p_nr_federate__p_0_self[0]->base.allocations);
            federate__p_nr_federate__p_0_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &federate__p_nr_federate__p_0_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    federate__p_nr_federate__p_0_self[0]->_lf__reaction_1.output_produced[count++] = &federate__p_nr_federate__p_0_self[0]->_lf_msg.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of federate__p.nr_federate__p_0
        
        }
        // **** End of deferred initialize for federate__p.nr_federate__p_0
        // **** Start deferred initialize for federate__p._pin10
        {
        
        
        
        }
        // **** End of deferred initialize for federate__p._pin10
        // **** Start deferred initialize for federate__p._pin20
        {
        
        
        
        }
        // **** End of deferred initialize for federate__p._pin20
    }
    // **** End of deferred initialize for federate__p
    // **** Start non-nested deferred initialize for federate__p
    
    
    
    // **** Start non-nested deferred initialize for federate__p.p
    
    
    
    
    // **** End of non-nested deferred initialize for federate__p.p
    // **** Start non-nested deferred initialize for federate__p.nr_federate__p
    
    // For reference counting, set num_destinations for port federate__p.nr_federate__p.msg.
    // Iterate over range federate__p.nr_federate__p.msg(0,1)->[federate__p.p.in1(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        federate__p_nr_federate__p_self[src_runtime]->_lf_msg._base.num_destinations = 1;
        federate__p_nr_federate__p_self[src_runtime]->_lf_msg._base.source_reactor = (self_base_t*)federate__p_nr_federate__p_self[src_runtime];
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range federate__p.nr_federate__p.msg(0,1)->[federate__p.p.in1(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of federate__p.nr_federate__p triggers 1 downstream reactions
            // through port federate__p.nr_federate__p.msg.
            federate__p_nr_federate__p_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of federate__p.nr_federate__p, allocate an
            // array of trigger pointers for downstream reactions through port federate__p.nr_federate__p.msg
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &federate__p_nr_federate__p_self[src_runtime]->base.allocations); 
            federate__p_nr_federate__p_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges federate__p.nr_federate__p.msg(0,1)->[federate__p.p.in1(0,1)] and federate__p.p.in1(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range federate__p.p.in1(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port federate__p.p.in1's trigger struct.
                federate__p_nr_federate__p_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &federate__p_p_self[dst_runtime]->_lf__in1;
            }
        }
    }
    
    // **** End of non-nested deferred initialize for federate__p.nr_federate__p
    // **** Start non-nested deferred initialize for federate__p.nr_federate__p_0
    
    // For reference counting, set num_destinations for port federate__p.nr_federate__p_0.msg.
    // Iterate over range federate__p.nr_federate__p_0.msg(0,1)->[federate__p.p.in2(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        federate__p_nr_federate__p_0_self[src_runtime]->_lf_msg._base.num_destinations = 1;
        federate__p_nr_federate__p_0_self[src_runtime]->_lf_msg._base.source_reactor = (self_base_t*)federate__p_nr_federate__p_0_self[src_runtime];
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range federate__p.nr_federate__p_0.msg(0,1)->[federate__p.p.in2(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of federate__p.nr_federate__p_0 triggers 1 downstream reactions
            // through port federate__p.nr_federate__p_0.msg.
            federate__p_nr_federate__p_0_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of federate__p.nr_federate__p_0, allocate an
            // array of trigger pointers for downstream reactions through port federate__p.nr_federate__p_0.msg
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &federate__p_nr_federate__p_0_self[src_runtime]->base.allocations); 
            federate__p_nr_federate__p_0_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges federate__p.nr_federate__p_0.msg(0,1)->[federate__p.p.in2(0,1)] and federate__p.p.in2(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range federate__p.p.in2(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port federate__p.p.in2's trigger struct.
                federate__p_nr_federate__p_0_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &federate__p_p_self[dst_runtime]->_lf__in2;
            }
        }
    }
    
    // **** End of non-nested deferred initialize for federate__p.nr_federate__p_0
    // **** Start non-nested deferred initialize for federate__p._pin10
    
    // For reference counting, set num_destinations for port federate__p._pin10.port.
    // Iterate over range federate__p._pin10.port(0,1)->[federate__p.p.in1(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        federate__p__pin10_self[src_runtime]->_lf_port._base.num_destinations = 1;
        federate__p__pin10_self[src_runtime]->_lf_port._base.source_reactor = (self_base_t*)federate__p__pin10_self[src_runtime];
    }
    
    
    // **** End of non-nested deferred initialize for federate__p._pin10
    // **** Start non-nested deferred initialize for federate__p._pin20
    
    // For reference counting, set num_destinations for port federate__p._pin20.port.
    // Iterate over range federate__p._pin20.port(0,1)->[federate__p.p.in2(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        federate__p__pin20_self[src_runtime]->_lf_port._base.num_destinations = 1;
        federate__p__pin20_self[src_runtime]->_lf_port._base.source_reactor = (self_base_t*)federate__p__pin20_self[src_runtime];
    }
    
    
    // **** End of non-nested deferred initialize for federate__p._pin20
    // **** End of non-nested deferred initialize for federate__p
    // Connect inputs and outputs for reactor federate__p.
    // Connect inputs and outputs for reactor federate__p.p.
    // Connect inputs and outputs for reactor federate__p.nr_federate__p.
    // Connect federate__p.nr_federate__p.msg(0,1)->[federate__p.p.in1(0,1)] to port federate__p.p.in1(0,1)
    // Iterate over ranges federate__p.nr_federate__p.msg(0,1)->[federate__p.p.in1(0,1)] and federate__p.p.in1(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range federate__p.p.in1(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            federate__p_p_self[dst_runtime]->_lf_in1 = (_print_in1_t*)&federate__p_nr_federate__p_self[src_runtime]->_lf_msg;
        }
    }
    // Connect inputs and outputs for reactor federate__p.nr_federate__p_0.
    // Connect federate__p.nr_federate__p_0.msg(0,1)->[federate__p.p.in2(0,1)] to port federate__p.p.in2(0,1)
    // Iterate over ranges federate__p.nr_federate__p_0.msg(0,1)->[federate__p.p.in2(0,1)] and federate__p.p.in2(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range federate__p.p.in2(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            federate__p_p_self[dst_runtime]->_lf_in2 = (_print_in2_t*)&federate__p_nr_federate__p_0_self[src_runtime]->_lf_msg;
        }
    }
    // Connect inputs and outputs for reactor federate__p._pin10.
    // Connect inputs and outputs for reactor federate__p._pin20.
    {
    }
    {
        {
            // Add action federate__p.nr_federate__p.networkMessage to array of is_present fields.
            envs[federate__p_main].is_present_fields[0] 
                    = &federate__p_nr_federate__p_self[0]->_lf_networkMessage.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add action federate__p.nr_federate__p.networkMessage to array of intended_tag fields.
            envs[federate__p_main]._lf_intended_tag_fields[0] 
                    = &federate__p_nr_federate__p_self[0]->_lf_networkMessage.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
        }
    }
    {
        {
            // Add action federate__p.nr_federate__p_0.networkMessage to array of is_present fields.
            envs[federate__p_main].is_present_fields[1] 
                    = &federate__p_nr_federate__p_0_self[0]->_lf_networkMessage.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add action federate__p.nr_federate__p_0.networkMessage to array of intended_tag fields.
            envs[federate__p_main]._lf_intended_tag_fields[1] 
                    = &federate__p_nr_federate__p_0_self[0]->_lf_networkMessage.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
        }
    }
    {
    }
    {
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port federate__p.nr_federate__p.msg to array of is_present fields.
            envs[federate__p_main].is_present_fields[2 + count] = &federate__p_nr_federate__p_self[0]->_lf_msg.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port federate__p.nr_federate__p.msg to array of intended_tag fields.
            envs[federate__p_main]._lf_intended_tag_fields[2 + count] = &federate__p_nr_federate__p_self[0]->_lf_msg.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port federate__p.nr_federate__p_0.msg to array of is_present fields.
            envs[federate__p_main].is_present_fields[3 + count] = &federate__p_nr_federate__p_0_self[0]->_lf_msg.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port federate__p.nr_federate__p_0.msg to array of intended_tag fields.
            envs[federate__p_main]._lf_intended_tag_fields[3 + count] = &federate__p_nr_federate__p_0_self[0]->_lf_msg.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
        }
    }
    
    // Set reaction priorities for ReactorInstance federate__p
    {
    
        // Set reaction priorities for ReactorInstance federate__p.p
        {
            federate__p_p_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 2 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            federate__p_p_self[0]->_lf__reaction_0.index = 0xffffffffffff0002LL;
            federate__p_p_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 4 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            federate__p_p_self[0]->_lf__reaction_1.index = 0xffffffffffff0004LL;
        }
    
    
        // Set reaction priorities for ReactorInstance federate__p.nr_federate__p
        {
            federate__p_nr_federate__p_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            federate__p_nr_federate__p_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            federate__p_nr_federate__p_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            federate__p_nr_federate__p_self[0]->_lf__reaction_1.index = 0xffffffffffff0001LL;
        }
    
    
        // Set reaction priorities for ReactorInstance federate__p.nr_federate__p_0
        {
            federate__p_nr_federate__p_0_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 2 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            federate__p_nr_federate__p_0_self[0]->_lf__reaction_0.index = 0xffffffffffff0002LL;
            federate__p_nr_federate__p_0_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 3 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            federate__p_nr_federate__p_0_self[0]->_lf__reaction_1.index = 0xffffffffffff0003LL;
        }
    
    }
    
    // Initialize the scheduler
    size_t num_reactions_per_level[5] = 
        {1, 1, 2, 1, 1};
    sched_params_t sched_params = (sched_params_t) {
                            .num_reactions_per_level = &num_reactions_per_level[0],
                            .num_reactions_per_level_size = (size_t) 5};
    lf_sched_init(
        &envs[federate__p_main],
        envs[federate__p_main].num_workers,
        &sched_params
    );
    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&envs[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        _lf_logical_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void terminate_execution(environment_t* env) {}
#endif
